/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ecobro;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import com.mycompany.views.*;

import javax.swing.*;
import java.awt.*;

/**
 * @author Mariano
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        initStyles();
        initContent();
    }

    /**
     * Initializes the style of the panel
     */
    private void initStyles() {
        lbl_titulo.putClientProperty("FlatLaf.style", "font: bold $h1.regular.font");
        lbl_titulo.setForeground(Color.BLACK);
        bt_AddVehiculo.setForeground(Color.BLACK);
        bt_UVehiculos.setForeground(Color.BLACK);
        bt_listaVehiculos.setForeground(Color.BLACK);
        content.setLayout(new BorderLayout());
    }

    /**
     * Initializes the content of the panel
     */
    private void initContent() {
        showJPanel(new UbicacionesVehiculos());
    }

    /**
     * Actualiza el contenido del panel principal al especificado
     *
     * @param p el nuevo panel a ser mostrado
     */
    public static void showJPanel(JPanel p) {
        p.setSize(content.getSize());
        p.setLocation(0, 0);

        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        bg_botones = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bt_UVehiculos = new javax.swing.JButton();
        bt_AddVehiculo = new javax.swing.JButton();
        bt_listaVehiculos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("eCobro");
        setPreferredSize(new java.awt.Dimension(1400, 600));

        bg.setBackground(new java.awt.Color(204, 204, 204));
        bg.setPreferredSize(new java.awt.Dimension(1600, 600));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setPreferredSize(new java.awt.Dimension(1200, 600));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
                contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1145, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
                contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
        );

        bg_botones.setBackground(new java.awt.Color(255, 255, 255));
        bg_botones.setPreferredSize(new java.awt.Dimension(382, 600));

        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("eCobro");
        lbl_titulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bt_UVehiculos.setBackground(new java.awt.Color(255, 255, 255));
        bt_UVehiculos.setText("Ubicaciones Vehiculos");
        bt_UVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_UVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_UVehiculosActionPerformed(evt);
            }
        });

        bt_AddVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        bt_AddVehiculo.setText("Agregar Vehiculo");
        bt_AddVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_AddVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AddVehiculoActionPerformed(evt);
            }
        });

        bt_listaVehiculos.setBackground(new java.awt.Color(255, 255, 255));
        bt_listaVehiculos.setText("Lista de Vehiculos");
        bt_listaVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_listaVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_listaVehiculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_botonesLayout = new javax.swing.GroupLayout(bg_botones);
        bg_botones.setLayout(bg_botonesLayout);
        bg_botonesLayout.setHorizontalGroup(
                bg_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bg_botonesLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bg_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSeparator1)
                                        .addComponent(bt_UVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                        .addComponent(bt_AddVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(bt_listaVehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        bg_botonesLayout.setVerticalGroup(
                bg_botonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bg_botonesLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bt_UVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_AddVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bt_listaVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(162, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
                bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bgLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bg_botones, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgLayout.setVerticalGroup(
                bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bgLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(bg_botones, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1427, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_UVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_UVehiculosActionPerformed
        showJPanel(new UbicacionesVehiculos());
    }//GEN-LAST:event_bt_UVehiculosActionPerformed

    private void bt_AddVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AddVehiculoActionPerformed
        showJPanel(new CargaVehiculo());
    }//GEN-LAST:event_bt_AddVehiculoActionPerformed

    private void bt_listaVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_listaVehiculosActionPerformed
        showJPanel(new ListaVehiculos());
    }//GEN-LAST:event_bt_listaVehiculosActionPerformed

    /**
     * Metodo principal
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatMaterialLighterIJTheme.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg_botones;
    private javax.swing.JButton bt_AddVehiculo;
    private javax.swing.JButton bt_UVehiculos;
    private javax.swing.JButton bt_listaVehiculos;
    private static javax.swing.JPanel content;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_titulo;
    // End of variables declaration//GEN-END:variables
}
